"""
multilingual.py
───────────────
Multilingual output system for the Smart Agriculture Platform.

Architecture (three-tier):
  Tier 1 — Static i18n strings: pre-translated JSON dictionaries
            for all UI labels, field names, section headers.
  Tier 2 — Template-based dynamic translation: advisory sentences
            built from parameterised templates per language.
  Tier 3 — Fallback to English for any untranslated key.

Supports: English (en), Hindi (hi), Tamil (ta), Telugu (te),
          Bengali (bn), Marathi (mr), Swahili (sw)

In production, Tier 2 is replaced by mT5 fine-tuned on agricultural
corpus — the interface (translate / localise_report) stays identical.
"""

from typing import Any


# ── Static translation strings ──────────────────────────────────────────────
STRINGS = {
    "en": {
        "app_name": "KhetAI — Smart Agriculture System",
        "crop_analysis": "Crop Analysis Report",
        "disease_detection": "Disease Detection",
        "soil_analysis": "Soil & Nutrient Analysis",
        "weather_analysis": "Weather Conditions",
        "yield_forecast": "Yield Forecast",
        "recommendations": "AI Recommendations",
        "fertilizer": "Fertilizer Recommendation",
        "irrigation": "Irrigation Advisory",
        "disease_treatment": "Disease Treatment",
        "crop_improvement": "Crop Improvement",
        "priority_action": "Priority Action",
        "soil_health": "Soil Health Score",
        "overall_score": "Overall Farm Score",
        "predicted_yield": "Predicted yield",
        "yield_range": "Expected range",
        "confidence": "Confidence",
        "limiting_factor": "Primary limiting factor",
        "grade": "Performance grade",
        "status_optimal": "Optimal",
        "status_low": "Below optimal",
        "status_critical": "Critical — act immediately",
        "healthy_msg": "No disease detected — crop appears healthy",
        "disease_msg": "Disease detected",
        "dose": "Dose",
        "timing": "Application timing",
        "frequency": "Frequency",
        "volume": "Volume",
        "method": "Method",
        "chemical": "Chemical treatment",
        "organic_alt": "Organic alternative",
        "impact": "Yield impact",
        "high_priority": "HIGH PRIORITY",
        "medium_priority": "MODERATE",
        "low_priority": "ADVISORY",
        "unit_t_ha": "tonnes/hectare",
        "unit_kg_ha": "kg/ha",
        "generated_by": "Generated by KhetAI",
    },
    "hi": {
        "app_name": "KhetAI — स्मार्ट कृषि प्रणाली",
        "crop_analysis": "फसल विश्लेषण रिपोर्ट",
        "disease_detection": "रोग पहचान",
        "soil_analysis": "मिट्टी और पोषक तत्व विश्लेषण",
        "weather_analysis": "मौसम की स्थिति",
        "yield_forecast": "उपज पूर्वानुमान",
        "recommendations": "AI सुझाव",
        "fertilizer": "उर्वरक सुझाव",
        "irrigation": "सिंचाई सलाह",
        "disease_treatment": "रोग उपचार",
        "crop_improvement": "फसल सुधार",
        "priority_action": "प्राथमिक कार्यवाही",
        "soil_health": "मिट्टी स्वास्थ्य स्कोर",
        "overall_score": "समग्र खेत स्कोर",
        "predicted_yield": "अनुमानित उपज",
        "yield_range": "संभावित सीमा",
        "confidence": "विश्वसनीयता",
        "limiting_factor": "मुख्य सीमित कारक",
        "grade": "प्रदर्शन ग्रेड",
        "status_optimal": "उचित",
        "status_low": "उचित से कम",
        "status_critical": "गंभीर — तत्काल कार्यवाही करें",
        "healthy_msg": "कोई रोग नहीं मिला — फसल स्वस्थ दिखती है",
        "disease_msg": "रोग का पता चला",
        "dose": "मात्रा",
        "timing": "आवेदन समय",
        "frequency": "आवृत्ति",
        "volume": "आयतन",
        "method": "विधि",
        "chemical": "रासायनिक उपचार",
        "organic_alt": "जैविक विकल्प",
        "impact": "उपज पर प्रभाव",
        "high_priority": "उच्च प्राथमिकता",
        "medium_priority": "मध्यम",
        "low_priority": "सलाह",
        "unit_t_ha": "टन/हेक्टेयर",
        "unit_kg_ha": "किग्रा/हेक्टेयर",
        "generated_by": "KhetAI द्वारा उत्पन्न",
    },
    "ta": {
        "app_name": "KhetAI — ஸ்மார்ட் விவசாய அமைப்பு",
        "crop_analysis": "பயிர் பகுப்பாய்வு அறிக்கை",
        "disease_detection": "நோய் கண்டறிதல்",
        "soil_analysis": "மண் மற்றும் ஊட்டச்சத்து பகுப்பாய்வு",
        "weather_analysis": "வானிலை நிலைமைகள்",
        "yield_forecast": "மகசூல் முன்னறிவிப்பு",
        "recommendations": "AI பரிந்துரைகள்",
        "fertilizer": "உர பரிந்துரை",
        "irrigation": "பாசன ஆலோசனை",
        "disease_treatment": "நோய் சிகிச்சை",
        "crop_improvement": "பயிர் மேம்பாடு",
        "priority_action": "முன்னுரிமை நடவடிக்கை",
        "soil_health": "மண் ஆரோக்கிய மதிப்பெண்",
        "overall_score": "மொத்த பண்ணை மதிப்பெண்",
        "predicted_yield": "கணிக்கப்பட்ட மகசூல்",
        "yield_range": "எதிர்பார்க்கப்படும் வரம்பு",
        "confidence": "நம்பகத்தன்மை",
        "limiting_factor": "முக்கிய கட்டுப்படுத்தும் காரணி",
        "grade": "செயல்திறன் தரம்",
        "status_optimal": "உகந்தது",
        "status_low": "குறைவாக",
        "status_critical": "அவசரம் — உடனடி நடவடிக்கை",
        "healthy_msg": "நோய் கண்டறியவில்லை — பயிர் ஆரோக்கியமாக உள்ளது",
        "disease_msg": "நோய் கண்டறியப்பட்டது",
        "dose": "அளவு",
        "timing": "விண்ணப்ப நேரம்",
        "frequency": "அதிர்வெண்",
        "volume": "அளவு",
        "method": "முறை",
        "chemical": "வேதியியல் சிகிச்சை",
        "organic_alt": "இயற்கை மாற்று",
        "impact": "மகசூல் தாக்கம்",
        "high_priority": "அதிக முன்னுரிமை",
        "medium_priority": "நடுத்தரம்",
        "low_priority": "ஆலோசனை",
        "unit_t_ha": "டன்/ஹெக்டேர்",
        "unit_kg_ha": "கிலோ/ஹெக்டேர்",
        "generated_by": "KhetAI ஆல் உருவாக்கப்பட்டது",
    },
    "sw": {
        "app_name": "KhetAI — Mfumo wa Kilimo Hodari",
        "crop_analysis": "Ripoti ya Uchambuzi wa Zao",
        "disease_detection": "Ugunduzi wa Ugonjwa",
        "soil_analysis": "Uchambuzi wa Udongo na Virutubisho",
        "weather_analysis": "Hali ya Hewa",
        "yield_forecast": "Utabiri wa Mavuno",
        "recommendations": "Mapendekezo ya AI",
        "fertilizer": "Pendekezo la Mbolea",
        "irrigation": "Ushauri wa Umwagiliaji",
        "disease_treatment": "Matibabu ya Ugonjwa",
        "crop_improvement": "Uboreshaji wa Zao",
        "priority_action": "Hatua ya Kipaumbele",
        "soil_health": "Alama ya Afya ya Udongo",
        "overall_score": "Alama ya Jumla ya Shamba",
        "predicted_yield": "Mavuno yanayotabiriwa",
        "yield_range": "Kiwango kinachotarajiwa",
        "confidence": "Kiwango cha Imani",
        "limiting_factor": "Sababu kuu inayozuia",
        "grade": "Daraja la Utendaji",
        "status_optimal": "Bora",
        "status_low": "Chini ya bora",
        "status_critical": "Dharura — chukua hatua mara moja",
        "healthy_msg": "Hakuna ugonjwa — zao linaonekana zuri",
        "disease_msg": "Ugonjwa umegunduliwa",
        "dose": "Kipimo",
        "timing": "Wakati wa kutumia",
        "frequency": "Mara ngapi",
        "volume": "Kiasi",
        "method": "Njia",
        "chemical": "Matibabu ya kemikali",
        "organic_alt": "Mbadala wa kikaboni",
        "impact": "Athari kwa mavuno",
        "high_priority": "KIPAUMBELE CHA JUU",
        "medium_priority": "WASTANI",
        "low_priority": "USHAURI",
        "unit_t_ha": "tani/hekta",
        "unit_kg_ha": "kg/hekta",
        "generated_by": "Imetolewa na KhetAI",
    },
    "te": {
        "app_name": "KhetAI — స్మార్ట్ వ్యవసాయ వ్యవస్థ",
        "crop_analysis": "పంట విశ్లేషణ నివేదిక",
        "disease_detection": "వ్యాధి గుర్తింపు",
        "soil_analysis": "నేల మరియు పోషక విశ్లేషణ",
        "weather_analysis": "వాతావరణ పరిస్థితులు",
        "yield_forecast": "దిగుబడి అంచనా",
        "recommendations": "AI సిఫార్సులు",
        "fertilizer": "ఎరువు సిఫార్సు",
        "irrigation": "నీటిపారుదల సలహా",
        "disease_treatment": "వ్యాధి చికిత్స",
        "crop_improvement": "పంట మెరుగుదల",
        "priority_action": "ప్రాధాన్య చర్య",
        "soil_health": "నేల ఆరోగ్య స్కోర్",
        "overall_score": "మొత్తం వ్యవసాయ స్కోర్",
        "predicted_yield": "అంచనా దిగుబడి",
        "yield_range": "అంచనా పరిధి",
        "confidence": "విశ్వాసం",
        "limiting_factor": "ప్రాథమిక పరిమిత కారకం",
        "grade": "పనితీరు గ్రేడ్",
        "status_optimal": "సరైనది",
        "status_low": "తక్కువ",
        "status_critical": "విపత్తు — వెంటనే చర్య",
        "healthy_msg": "వ్యాధి కనుగొనబడలేదు — పంట ఆరోగ్యంగా ఉంది",
        "disease_msg": "వ్యాధి కనుగొనబడింది",
        "dose": "మోతాదు",
        "timing": "దరఖాస్తు సమయం",
        "frequency": "పౌనఃపున్యం",
        "volume": "పరిమాణం",
        "method": "పద్ధతి",
        "chemical": "రసాయన చికిత్స",
        "organic_alt": "సేంద్రీయ ప్రత్యామ్నాయం",
        "impact": "దిగుబడి ప్రభావం",
        "high_priority": "అధిక ప్రాధాన్యత",
        "medium_priority": "మధ్యస్థ",
        "low_priority": "సలహా",
        "unit_t_ha": "టన్నులు/హెక్టారు",
        "unit_kg_ha": "కిలో/హెక్టారు",
        "generated_by": "KhetAI ద్వారా రూపొందించబడింది",
    },
    "bn": {
        "app_name": "KhetAI — স্মার্ট কৃষি ব্যবস্থা",
        "crop_analysis": "ফসল বিশ্লেষণ রিপোর্ট",
        "disease_detection": "রোগ সনাক্তকরণ",
        "soil_analysis": "মাটি ও পুষ্টি বিশ্লেষণ",
        "weather_analysis": "আবহাওয়ার অবস্থা",
        "yield_forecast": "ফলন পূর্বাভাস",
        "recommendations": "AI সুপারিশ",
        "fertilizer": "সার সুপারিশ",
        "irrigation": "সেচ পরামর্শ",
        "disease_treatment": "রোগের চিকিৎসা",
        "crop_improvement": "ফসল উন্নয়ন",
        "priority_action": "অগ্রাধিকার পদক্ষেপ",
        "soil_health": "মাটির স্বাস্থ্য স্কোর",
        "overall_score": "সামগ্রিক খামার স্কোর",
        "predicted_yield": "প্রত্যাশিত ফলন",
        "yield_range": "প্রত্যাশিত পরিসীমা",
        "confidence": "আস্থা",
        "limiting_factor": "প্রধান সীমাবদ্ধ উপাদান",
        "grade": "কর্মক্ষমতা গ্রেড",
        "status_optimal": "সর্বোত্তম",
        "status_low": "সর্বোত্তমের নিচে",
        "status_critical": "জরুরি — অবিলম্বে পদক্ষেপ নিন",
        "healthy_msg": "কোনো রোগ পাওয়া যায়নি — ফসল সুস্থ দেখাচ্ছে",
        "disease_msg": "রোগ সনাক্ত হয়েছে",
        "dose": "মাত্রা",
        "timing": "প্রয়োগের সময়",
        "frequency": "কতবার",
        "volume": "পরিমাণ",
        "method": "পদ্ধতি",
        "chemical": "রাসায়নিক চিকিৎসা",
        "organic_alt": "জৈব বিকল্প",
        "impact": "ফলনে প্রভাব",
        "high_priority": "উচ্চ অগ্রাধিকার",
        "medium_priority": "মাঝারি",
        "low_priority": "পরামর্শ",
        "unit_t_ha": "টন/হেক্টর",
        "unit_kg_ha": "কেজি/হেক্টর",
        "generated_by": "KhetAI দ্বারা তৈরি",
    },
    "mr": {
        "app_name": "KhetAI — स्मार्ट शेती प्रणाली",
        "crop_analysis": "पीक विश्लेषण अहवाल",
        "disease_detection": "रोग ओळख",
        "soil_analysis": "माती आणि पोषक विश्लेषण",
        "weather_analysis": "हवामानाची परिस्थिती",
        "yield_forecast": "उत्पादन अंदाज",
        "recommendations": "AI शिफारसी",
        "fertilizer": "खत शिफारस",
        "irrigation": "सिंचन सल्ला",
        "disease_treatment": "रोग उपचार",
        "crop_improvement": "पीक सुधारणा",
        "priority_action": "प्राधान्य कृती",
        "soil_health": "माती आरोग्य गुण",
        "overall_score": "एकूण शेत गुण",
        "predicted_yield": "अपेक्षित उत्पादन",
        "yield_range": "अपेक्षित श्रेणी",
        "confidence": "विश्वासार्हता",
        "limiting_factor": "मुख्य मर्यादित घटक",
        "grade": "कामगिरी श्रेणी",
        "status_optimal": "इष्टतम",
        "status_low": "इष्टतमपेक्षा कमी",
        "status_critical": "आपत्कालीन — त्वरित कार्यवाही",
        "healthy_msg": "कोणताही रोग आढळला नाही — पीक निरोगी दिसत आहे",
        "disease_msg": "रोग आढळला",
        "dose": "मात्रा",
        "timing": "अर्ज वेळ",
        "frequency": "वारंवारता",
        "volume": "प्रमाण",
        "method": "पद्धत",
        "chemical": "रासायनिक उपचार",
        "organic_alt": "सेंद्रिय पर्याय",
        "impact": "उत्पादनावर परिणाम",
        "high_priority": "उच्च प्राधान्य",
        "medium_priority": "मध्यम",
        "low_priority": "सल्ला",
        "unit_t_ha": "टन/हेक्टर",
        "unit_kg_ha": "किलो/हेक्टर",
        "generated_by": "KhetAI द्वारे तयार केले",
    },
}

SUPPORTED_LANGUAGES = list(STRINGS.keys())


class MultilingualOutput:
    """
    Translates recommendation reports into target languages.

    Usage:
        ml = MultilingualOutput(lang="hi")
        report = ml.localise_report(full_result)
        ml.print_report(report)
    """

    def __init__(self, lang: str = "en"):
        self.lang = lang if lang in STRINGS else "en"
        self._s = STRINGS[self.lang]

    def t(self, key: str, fallback: str = "") -> str:
        """Translate a key, with English fallback."""
        result = self._s.get(key)
        if result:
            return result
        return STRINGS["en"].get(key, fallback or key)

    def localise_report(self, full_result: dict) -> dict:
        """
        Takes the full pipeline output dict and returns a language-localised
        version ready for display.
        """
        s = self.t
        yr = full_result.get("yield_result", {})
        sw = full_result.get("soil_weather_result", {})
        dr = full_result.get("disease_result", {})
        rr = full_result.get("recommendations", {})
        crop = full_result.get("crop", "wheat")

        report = {
            "title":       f"{s('app_name')} | {s('crop_analysis')} — {crop.title()}",
            "language":    self.lang,
            "sections": {
                "disease": self._localise_disease(dr, s),
                "soil_weather": self._localise_soil_weather(sw, s),
                "yield": self._localise_yield(yr, s),
                "recommendations": self._localise_recs(rr, s),
            },
            "summary": {
                s("overall_score"):  rr.get("overall_score", "—"),
                s("predicted_yield"): f"{yr.get('predicted_yield','—')} {s('unit_t_ha')}",
                s("priority_action"): rr.get("priority_action", "—"),
                s("grade"):          yr.get("grade", "—"),
            },
        }
        return report

    def _localise_disease(self, dr, s):
        if not dr:
            return {"heading": s("disease_detection"), "text": s("healthy_msg"), "priority": "none"}
        is_h = dr.get("is_healthy", True)
        return {
            "heading": s("disease_detection"),
            "text": s("healthy_msg") if is_h else f"{s('disease_msg')}: {dr.get('top_disease','').replace('_',' ').title()}",
            "confidence": f"{dr.get('confidence',0):.1%}",
            "severity":   dr.get("severity", "none"),
            "top3":       [(d.replace("_"," ").title(), f"{p:.1%}") for d, p in dr.get("top3", [])],
            "priority":   "none" if is_h else ("critical" if dr.get("severity")=="critical" else "high"),
        }

    def _localise_soil_weather(self, sw, s):
        if not sw:
            return {}
        nutrients = sw.get("nutrients", {})
        return {
            "heading": s("soil_analysis"),
            "soil_health": f"{sw.get('soil_health_score', 0)}/100",
            "nutrients": {
                k: {
                    "value": f"{v.get('value',0):.0f} {s('unit_kg_ha')}",
                    "status": self._translate_status(v.get("status",""), s),
                    "remedy": v.get("remedy",""),
                }
                for k, v in nutrients.items() if k != "limiting_nutrient"
            },
            "limiting_nutrient": nutrients.get("limiting_nutrient", "—"),
            "ph": {
                "value": sw.get("ph_analysis", {}).get("value", "—"),
                "status": self._translate_status(sw.get("ph_analysis", {}).get("status", ""), s),
                "action": sw.get("ph_analysis", {}).get("action", ""),
            },
            "weather_heading": s("weather_analysis"),
            "temperature": sw.get("weather_analysis", {}).get("temperature", {}).get("value", "—"),
            "humidity":    sw.get("weather_analysis", {}).get("humidity", {}).get("value", "—"),
        }

    def _localise_yield(self, yr, s):
        if not yr:
            return {}
        low, high = yr.get("yield_range", (0, 0))
        return {
            "heading": s("yield_forecast"),
            s("predicted_yield"):  f"{yr.get('predicted_yield','—')} {s('unit_t_ha')}",
            s("yield_range"):      f"{low}–{high} {s('unit_t_ha')}",
            s("confidence"):       f"{yr.get('confidence',0):.0%}",
            s("limiting_factor"):  yr.get("limiting_factor","—"),
            s("grade"):            yr.get("grade","—"),
            "improvement": f"+{yr.get('improvement_potential',0):.1f} {s('unit_t_ha')} potential",
        }

    def _localise_recs(self, rr, s):
        if not rr:
            return {}
        fertilizer = []
        for r in rr.get("fertilizer", []):
            fertilizer.append({
                "action":  r.get("action",""),
                s("dose"):   r.get("dose","—"),
                s("timing"): r.get("timing","—"),
                "priority":  self._translate_priority(r.get("priority",""), s),
            })

        irr = rr.get("irrigation", {})
        irrigation = {
            "heading":     s("irrigation"),
            s("frequency"): irr.get("frequency","—"),
            s("volume"):    irr.get("volume","—"),
            s("method"):    irr.get("method","—"),
            "note":         irr.get("note",""),
        }

        treatment = []
        for r in rr.get("disease_treatment", []):
            treatment.append({
                "disease":       r.get("disease",""),
                s("chemical"):   r.get("chemical_treatment","—"),
                s("organic_alt"):r.get("organic_alternative","—"),
                s("frequency"):  r.get("spray_interval","—"),
                "priority":      self._translate_priority(r.get("priority",""), s),
            })

        improvement = []
        for r in rr.get("crop_improvement", []):
            improvement.append({
                "action":    r.get("action",""),
                "technique": r.get("technique",""),
            })

        return {
            "heading":      s("recommendations"),
            "fertilizer":   fertilizer,
            "irrigation":   irrigation,
            "treatment":    treatment,
            "improvement":  improvement,
            "priority":     rr.get("priority_action",""),
        }

    def _translate_status(self, status: str, s) -> str:
        if status == "optimal":          return s("status_optimal")
        if "low" in status:              return s("status_low")
        if "critical" in status:        return s("status_critical")
        return status.replace("_"," ").title()

    def _translate_priority(self, priority: str, s) -> str:
        if priority in ("critical","high"): return s("high_priority")
        if priority == "medium":            return s("medium_priority")
        return s("low_priority")

    def print_report(self, report: dict, width: int = 72) -> None:
        """Pretty-print the localised report to stdout."""
        bar  = "═" * width
        thin = "─" * width

        def hdr(text): print(f"\n{bar}\n  {text}\n{bar}")
        def sub(text): print(f"\n{thin}\n  {text}\n{thin}")
        def row(k, v, indent=2): print(f"{'  '*indent}{k}: {v}")

        hdr(report.get("title","KhetAI Report"))

        # ── Summary ──────────────────────────────────────────────────
        sub("📋 Summary")
        for k, v in report.get("summary", {}).items():
            row(k, v)

        secs = report.get("sections", {})

        # ── Disease ───────────────────────────────────────────────────
        d = secs.get("disease", {})
        sub(f"🔬 {d.get('heading','Disease')}")
        print(f"  {d.get('text','')}")
        if d.get("confidence"):
            row("Confidence", d["confidence"])
            row("Severity",   d["severity"])
            print("  Top candidates:")
            for name, prob in d.get("top3",[]):
                print(f"    • {name:<28} {prob}")

        # ── Soil ──────────────────────────────────────────────────────
        sw = secs.get("soil_weather", {})
        sub(f"🌱 {sw.get('heading','Soil')}")
        row("Soil health", sw.get("soil_health",""))
        for nut, info in sw.get("nutrients", {}).items():
            print(f"  {nut} → {info.get('value','')} [{info.get('status','')}]")
            if info.get("remedy","") and info["remedy"] != "No action needed":
                print(f"       ↳ {info['remedy']}")
        ph = sw.get("ph", {})
        row(f"pH {ph.get('value','')}", f"{ph.get('status','')} — {ph.get('action','')}")

        # ── Yield ─────────────────────────────────────────────────────
        yl = secs.get("yield", {})
        sub(f"📈 {yl.get('heading','Yield')}")
        for k, v in yl.items():
            if k not in ("heading", "improvement"):
                row(k, v)
        if yl.get("improvement"):
            print(f"  ↑ {yl['improvement']}")

        # ── Recommendations ───────────────────────────────────────────
        rc = secs.get("recommendations", {})
        sub(f"💡 {rc.get('heading','Recommendations')}")

        if rc.get("fertilizer"):
            print(f"  {self.t('fertilizer')}:")
            for r in rc["fertilizer"]:
                print(f"    [{r['priority']}] {r.get('action','')}")
                for k, v in r.items():
                    if k not in ("action","priority"): row(k, v, indent=3)

        irr = rc.get("irrigation", {})
        if irr:
            print(f"\n  {irr.get('heading',self.t('irrigation'))}:")
            for k, v in irr.items():
                if k not in ("heading",): row(k, v, indent=3)

        if rc.get("treatment"):
            print(f"\n  {self.t('disease_treatment')}:")
            for r in rc["treatment"]:
                print(f"    [{r['priority']}] {r.get('disease','')}")
                for k, v in r.items():
                    if k not in ("disease","priority"): row(k, v, indent=3)

        if rc.get("improvement"):
            print(f"\n  {self.t('crop_improvement')}:")
            for r in rc["improvement"]:
                print(f"    • {r.get('action','')} → {r.get('technique','')}")

        print(f"\n{bar}")
        print(f"  {self.t('generated_by')} | Language: {self.lang.upper()}")
        print(f"{bar}\n")